export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="bira"
plugins=(
  git
  docker
  docker-compose
  kubectl
  fzf-zsh-plugin
  fzf-tab
)
# TMUX
export TERM=xterm-256color
set -g default-terminal "${TERM}"
#set -ga terminal-overrides ",xterm-256color:Tc,alacritty:RGB"

# PYTHON
if command -v pyenv 1>/dev/null 2>&1; then
 eval "$(pyenv init -)"
 eval "$(pyenv init --path)" 
fi

export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

# FLUTTER
export PATH="$PATH:$HOME/flutter/bin"

# VSCODE 
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

source $ZSH/oh-my-zsh.sh
alias vim=nvim
export PATH="$PATH:$HOME/.config/nvim/kotlin-debug-adapter"


function work() {
  local dir=$1

  if [ -z "$TMUX" ]; then
    echo "⚠️  start tmux session first"
    return
  fi
  cd ~/projects/$dir

	tmux new-window -n "$dir" -c "$project_dir"

	tmux send-keys "nvim ." C-m

	tmux split-window -v -c "$project_dir"
	tmux send-keys "clear" C-m

	tmux select-pane -U
	tmux split-window -h -c "$project_dir"
	tmux send-keys "aider" C-m
	tmux resize-pane -t 1 -x 30%
	tmux resize-pane -t 2 -y 10%
	tmux select-pane -R
cd -
}

local SUBPROJECTS=("MONETISATION" "carramba") 

_work() {
  local base=~/projects
  local search_dirs=("$base")
  local candidates=()

  for subproject in "${SUBPROJECTS[@]}"; do
    [ -d "$base/$subproject" ] && search_dirs+=("$base/$subproject")
  done

  for d in "${search_dirs[@]}"; do
    for dir in "$d"/*; do
      [ -d "$dir" ] || continue
      local name
      if [[ "$d" != "$base" ]]; then
        name="$(basename "$d")/$(basename "$dir")"
      else
        name="$(basename "$dir")"
      fi
      candidates+=("$name")
    done
  done

  _arguments "1:project:(${candidates[*]})"
}
compdef _work work
