export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="bira"
plugins=(
  git
  docker
  docker-compose
  fzf-zsh-plugin
  fzf-tab
)
# TMUX
export TERM=xterm-256color
set -g default-terminal "${TERM}"
#set -ga terminal-overrides ",xterm-256color:Tc,alacritty:RGB"

# PYTHON
if command -v pyenv 1>/dev/null 2>&1; then
 eval "$(pyenv init -)"
 eval "$(pyenv init --path)" 
fi

export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

# FLUTTER
export PATH="$PATH:$HOME/flutter/bin"

# VSCODE 
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

source $ZSH/oh-my-zsh.sh
alias vim=nvim
export PATH="$PATH:$HOME/.config/nvim/kotlin-debug-adapter"
